[package]
name = "cube"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cubecl = { version = "0.9" }

[features]
default = ["wgpu"]
wgpu = ["cubecl/wgpu"]
cuda = ["cubecl/cuda"]
cpu = ["cubecl/cpu"]

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "cube"
harness = false
