[package]
name = "cube"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cubecl = { git = "https://github.com/tracel-ai/cubecl", branch = "main" }
enum_dispatch = "0.3"
petgraph = "0.8"
rustc-hash = "2.1"

[features]
default = ["wgpu"]
wgpu = ["cubecl/wgpu"]
cuda = ["cubecl/cuda"]
cpu = ["cubecl/cpu"]

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "cube"
harness = false
