[package]
name = "rwkv"
version = "0.1.0"
edition = "2024"

[dependencies]
luminal = { path = "../.." }
luminal_nn = { path = "../../crates/luminal_nn" }
luminal_tracing = { path = "../../crates/luminal_tracing" }
rwkv-tokenizer = "0.9.1"
# CUDA
luminal_cuda = { path = "../../crates/luminal_cuda", optional = true }
# Metal
luminal_metal = { path = "../../crates/luminal_metal", optional = true }

[features]
default = []
cuda = ["dep:luminal_cuda"]
metal = ["dep:luminal_metal"]
